### ISSUE TITLE
Too many console log messages in SideNav

### ISSUE THREAD

**Issue by tbayne** [wmira/reactor-ui#1]
Just noticed that this litters the console log with lots of non-essential messages.  For example:

NavItem.js:74 is group section here  true
NavItem.js:74 is group section here  true
3NavItem.js:74 is group section here  false
NavItem.js:74 is group section here  true
NavItem.js:74 is group section here  true
3NavItem.js:74 is group section here  false
NavItem.js:74 is group section here  true
NavItem.js:74 is group section here  true
3NavItem.js:74 is group section here  false
NavItem.js:74 is group section here  true
NavItem.js:74 is group section here  true
3NavItem.js:74 is group section here  false
NavLeft.js:31 Currently Selected Item: hosts
SideNav.js:78 selectedId  danger hosts

**Comment by wmira** [comment]
@tbayne Thanks tbayne I have merged your PR

**Comment by tbayne** [comment]
Thanks, could you do a new release when you get a chance?  That way I can pick it up via npm update.
